### ISSUE TITLE
Add support for CaseStyle.camelCase

### ISSUE THREAD

**Issue by diegoveloper** [bratan/flutter_translate_annotations#1]
When generating the keys values, it would be great if we have the option to generate the constants using camel case.

**Comment by bratan** [comment]
Implemented in https://github.com/Jesway/Flutter-Translate-Annotations/commit/9f739b9738047f92c8d3f39c8c106e947b4e7a50

**Comment by MostafaSolimanMO** [comment]
It doesn't work (The camel case option)
